# Generated by Django 4.2 on 2025-04-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("male_rabbits", models.IntegerField()),
                ("female_rabbits", models.IntegerField()),
                ("foodLevel", models.IntegerField()),
                ("cageNumber", models.IntegerField()),
                ("money", models.IntegerField()),
                ("month", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="MaleRabbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "elevage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="males",
                        to="game.elevage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FemaleRabbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("pregnancyTime", models.IntegerField(default=0)),
                (
                    "elevage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="females",
                        to="game.elevage",
                    ),
                ),
            ],
        ),
    ]
