# Generated by Django 4.2 on 2025-04-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Individu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("sold", "Sold"),
                            ("dead", "Dead"),
                            ("pregnant", "Pregnant"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                (
                    "elevage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individus",
                        to="game.elevage",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="malerabbit",
            name="elevage",
        ),
        migrations.DeleteModel(
            name="FemaleRabbit",
        ),
        migrations.DeleteModel(
            name="MaleRabbit",
        ),
    ]
