# Generated by Django 4.2 on 2025-04-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_individu_remove_malerabbit_elevage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_price", models.IntegerField(default=5)),
                ("cage_price", models.IntegerField(default=50)),
                ("rabbit_sale_price", models.IntegerField(default=10)),
            ],
        ),
    ]
