# Generated by Django 4.2 on 2025-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_regle"),
    ]

    operations = [
        migrations.AddField(
            model_name="regle",
            name="food_consumption_age_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="regle",
            name="food_consumption_age_2",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="regle",
            name="food_consumption_age_3_or_more",
            field=models.IntegerField(default=250),
        ),
    ]
