# Generated by Django 4.2 on 2025-04-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_regle_food_consumption_age_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="individu",
            name="pregnancy_start_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="regle",
            name="gestation_duration",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="regle",
            name="litter_size",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="regle",
            name="reproduction_end_age",
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name="regle",
            name="reproduction_start_age",
            field=models.IntegerField(default=6),
        ),
    ]
