# Generated by Django 4.2 on 2025-04-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_individu_pregnancy_start_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regle",
            name="overpopulation_threshold",
            field=models.IntegerField(default=10),
        ),
    ]
