# Generated by Django 4.2 on 2025-04-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_regle_overpopulation_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="regle",
            name="budget_limit",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="regle",
            name="female_rabbit_price",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="regle",
            name="male_rabbit_price",
            field=models.IntegerField(default=10),
        ),
    ]
